$kind: http-request
url: http://localhost:8083/api/v1/inventario/productos
method: POST
headers:
  Content-Type: application/json
body:
  type: text
  content: |-
    {
      "sku": "ALI-001",
      "nombre": "Alimento perro adulto 15kg",
      "descripcion": "Alimento balanceado",
      "precio": 35990.0,
      "activo": true
    }
order: 2000
